### ISSUE TITLE
Cannot use Singleplayer

### ISSUE THREAD

**Issue by lafayettecinder** [LyraelRayne/StacysWolves#37] opened 2017-08-01 22:13 UTC
I've been having trouble using the mod, everytime I go onto singleplayer it crashes. I do not know if this is from forge or from the mod.
It shows this image 
![kkk](https://user-images.githubusercontent.com/30638726/28849459-b2e39092-76dc-11e7-81c7-3fd03b267270.PNG)
I've used forge 1.7.10 before with old mods that I now don't have on my new PC

**Comment by LyraelRayne** [comment] 2017-08-02 00:10
Can you put your latest.log from your profile's log directory into pastebin and link it here?

**Comment by lafayettecinder** [comment] 2017-08-02 00:49
I'll try!

**Comment by lafayettecinder** [comment] 2017-08-02 00:53
I'm sorry, how do I use it? I have a new computer and it's not the same as my old one

**Comment by SnowShock35** [comment] 2017-08-02 09:18
If you're on a Microsoft Windows computer you'll find the log at `%appdata%\.minecraft\logs`

If you're on a Mac OS computer you'll find the log at `~/Library/Application Support/minecraft/logs`

Keep in mind that if you're on a Mac that folder might be hidden by default. If you need help with that please refer to an online guide. 

Once you've found the log, open it up in a text editor (Notepad on Windows is fine). Now right click in the document and select the `Select All` option. then repeat this step, but select the `Copy` option. 

Next, go to https://pastebin.com/ once there, paste the contents by right clicking on the text box and clicking the `Paste` option. Then, scroll to the bottom and click `Create New Paste`.

Now, copy the web address at the top of the page (should look something like: `https://pastebin.com/Xfwwjn3`) paste it in a comment on here.

**Comment by LyraelRayne** [comment] 2017-08-02 09:38
Thanks @SnowShock35 

It'll be a little different if Twitch client is being used. In that case you need to right click on the profile in the minecraft section of Twitch and choose "Open Folder" This will open the location of your profile at which point you can double click on "logs" and the rest is as per Snow's previous comment. 
![image](https://user-images.githubusercontent.com/11632412/28867653-204f38a6-77ba-11e7-971b-df29d6b3170a.png)

**Comment by lafayettecinder** [comment] 2017-08-02 17:06
THANK YOU SNOWSHOCK!! Sorry about disturbing you and messaging instead of coming here!! I use a Windows, so I'll use it via %appdata%.
--
Just opened the recent log. It wasn't the right date because it's the 24th it says on the date but I'll tell you when I get the log that is for the 1st of August. 
https://pastebin.com/BrTpcqTm

**Comment by lafayettecinder** [comment] 2017-08-02 23:36
Here's the one that was _the actual date._
https://pastebin.com/CDFh3Qj4

**Comment by lafayettecinder** [comment] 2017-08-03 01:03
There's a ne
![sooo](https://user-images.githubusercontent.com/30638726/28901403-72f44436-77bd-11e7-8816-ffafbcd98bf8.PNG)
w problem now. 
I tried to delete the one that isn't (1) so I could see if it worked, but it wouldn't delete. I'm not asking for help but if you _do_ give me some tips I'll take them.

**Comment by LyraelRayne** [comment] 2017-08-03 11:35
Those logs I don't think are the right file. It's showing up as garbage (e.g. `®áE;‰ºµÜ‘0ü±wþJ_Òûdl÷G¯­¤Oâ7ôfü†öÉÃ•Aã®b?L®|`) in pastebin. The file should contain  text something like https://pastebin.com/SPy840qC (just a random other log)

The error you're getting in the new screenshot is because you have installed two copies of the mod. You're on the right track trying to delete one of them, but you won't be able to do that while the game is running. Try making sure the game is closed, or even rebooting the computer and then attempting to delete the offending duplicate.

**Comment by lafayettecinder** [comment] 2017-08-03 21:22
Thanks about the duplicate.
I deleted both the mods and I'm gonna reinstall them, and about the logs that is really weird.

**Comment by lafayettecinder** [comment] 2017-08-03 21:39
The log isn't the right file. Got it.
Found the right one.
https://pastebin.com/QjkmHUTj

**Comment by LyraelRayne** [comment] 2017-08-04 00:21
There appear to be a lot of errors in C:\Users\janab\AppData\Roaming\\.minecraft\saves\Moonlight Adventures\level.dat
java.lang.NullPointerException: null

I'm not sure if this is the cause of your problem, but you might want to try moving the Moonlight Adventures save out of your saves folder and see if that helps you.

**Comment by lafayettecinder** [comment] 2017-08-04 02:16
Oh where's that? Just wondering :)

**Comment by LyraelRayne** [comment] 2017-08-04 08:31
C:\Users\janab\AppData\Roaming\\.minecraft\saves\Moonlight Adventures is located in  C:\Users\janab\AppData\Roaming\\.minecraft\saves ;)

**Comment by lafayettecinder** [comment] 2017-08-05 22:01
mk

**Comment by lafayettecinder** [comment] 2017-08-05 22:10
but, it doesn't work

**Comment by LyraelRayne** [comment] 2017-08-06 00:09
OK can you give us a new log now that you're running without the broken world save?

Also if you could give us what comes up when you click "view crash report" it'd be helpful as well.

**Comment by lafayettecinder** [comment] 2017-08-08 03:24
so, I clicked it (view crash report) and it didn't do anything.
but i used the latest log ;) or at least what said latest log
https://pastebin.com/KRx7cgnr

**Comment by lafayettecinder** [comment] 2017-08-08 03:25
I would've gone and blocked off my mother's name but that would take too long

**Comment by LyraelRayne** [comment] 2017-08-08 11:16
[21:33:10] [main/INFO] [FML/]: Forge Mod Loader version 14.21.1.2443 for Minecraft 1.12 loading
<--- this is your problem. Stacy's wolves is for 1.7.10 only!

**Comment by lafayettecinder** [comment] 2017-08-10 20:03
uhh i've been using 1.7.10 all this time? i usually use 1.12 is the thing tho xD
![forge](https://user-images.githubusercontent.com/30638726/29189671-0b7e3368-7ddd-11e7-852e-77cf683a321e.PNG)

**Comment by LyraelRayne** [comment] 2017-08-10 23:48
Well the log you sent us is from 1.12 using forge 14.21.1.2443

If you're using multiple versions of Minecraft I recommend using Twitch Client (https://mods.curse.com/client) to manage the different profiles to make sure that each Minecraft installation is separate. Using that not only will it make sure your Minecraft versions are kept separate, it will make it easier to download and install mods. It will also keep them up to date for you.

As far as making this work with the vanilla launcher goes, I've not used that in years so maybe @SnowShock35  can provide some advice.

**Comment by LyraelRayne** [comment] 2017-08-11 12:35
My bad if I didn't explain this well enough, but you need to make the game crash, and then send us the latest log straight after. Maybe you had played 1.12 after playing with 1.7.10 and that's why your log is from 1.12?

**Comment by lafayettecinder** [comment] 2017-08-22 00:14
maybe

**Comment by lafayettecinder** [comment] 2017-08-22 00:14
sorry i didn't reply sooner, i'm moving so im very busy!!

**Comment by LyraelRayne** [comment] 2017-08-22 11:07
Not a problem, get the log when you can and we'll see if we can get you playing!

**Comment by lafayettecinder** [comment] 2017-08-24 01:09
mk

**Comment by lafayettecinder** [comment] 2017-09-04 17:06
OMG IT WORKED!!!

**Comment by lafayettecinder** [comment] 2017-09-04 17:09
![flowerwolf](https://user-images.githubusercontent.com/30638726/30034867-e8ded632-9169-11e7-86ed-ab7cefc728e3.PNG)

**Comment by LyraelRayne** [comment] 2017-09-05 00:14
Awesome. Did you do anything? Or did it just start working?

Also just a heads up that a new beta version was put up on curse yesterday which will hopefully become an official release sometime in the next week or so (as long as nobody finds problems). This will add sixteen new wolves to play with and collect.

I'm going to close this issue now, but you can still reply if you like.

**Closed as completed by LyraelRayne** 2017-09-05 00:14 UTC

**Comment by lafayettecinder** [comment] 2017-09-05 21:45
alrightttt
it started working when i updated it to the beta x3
and also...
THE NEW UPDATE IS SO ADORABLE GR8 JOB
